language: php
php:
  - "5.5"
  - "5.4"

before_script:
  - composer install


before_script:
  - composer require satooshi/php-coveralls:dev-master --dev --no-progress --prefer-source

script:
  - cd tests


# after_script:
# - php vendor/bin/coveralls -v
