language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"

before_script:
  - composer install --install-suggests --dev --no-interaction

script:
  - mkdir -p build/logs
  - phpunit


after_script:
  - php vendor/bin/coveralls -v
